
INSERT INTO Champion VALUES("Aatrox", 'Other','THE DARKIN BLADE','Darkin', 'Runeterra (Unknown)',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Aatrox_0', SINGLE_BLOB) as IMAGE) , "“I must destroy even hope…”", 2013-06-13);
INSERT INTO Champion VALUES("Ahri", 'Female', 'THE NINE-TAILED FOX','Vastayan', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Ahri_0.jpg', SINGLE_BLOB) as IMAGE) , "“Human emotions can be more volatile than even the deepest magic.”", 2011-12-14);
INSERT INTO Champion VALUES("Akali", 'Female', 'THE ROGUE ASSASSIN','Human', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Akali_0.jpg', SINGLE_BLOB) as IMAGE) , "“If you look dangerous, you better be dangerous.”", 2010-05-11);
INSERT INTO Champion VALUES("Akshan", 'Male', 'THE ROGUE SENTINEL','Human', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Akshan_0.jpg', SINGLE_BLOB) as IMAGE) , "“Not everything happens for a reason. Some things need to be sorted out.”", 2021-07-22);
INSERT INTO Champion VALUES("Alistar", 'Male', 'THE MINOTAUR','Other', 'Runeterra (Unknown)',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Alistar_0.jpg', SINGLE_BLOB) as IMAGE) , "“Nothing can hold me back!”", 2009-02-21);
INSERT INTO Champion VALUES("Amumu", 'Male', 'THE SAD MUMMY','Yordle', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Amumu_0.jpg', SINGLE_BLOB) as IMAGE) , "“Solitude can be lonelier than death.”", 2009-06-26);
INSERT INTO Champion VALUES("Anivia", 'Female', 'THE CRYOPHOENIX','Spirit God', 'Freljord',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Anivia_0.jpg', SINGLE_BLOB) as IMAGE) , "“I am the fury of the blizzard, the bite of the wind, and the cold of the ice. I am the Freljord.”", 2009-07-10);
INSERT INTO Champion VALUES("Annie", 'Female', 'THE DARK CHILD','Human', 'Runeterra (Unknown)',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Annie_0.jpg', SINGLE_BLOB) as IMAGE) , "“Ashes, ashes, they all fall down.”", 2009-02-21);
INSERT INTO Champion VALUES("Aphelios", 'Male', 'THE WEAPON OF THE FAITHFUL','Human', 'Targon',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Aphelios_0.jpg', SINGLE_BLOB) as IMAGE) , "“Our faith is proven fate each time we deny it.”", 2019-12-11);
INSERT INTO Champion VALUES("Ashe", 'Female', 'THE FROST ARCHER','Human', 'Freljord',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\_0.jpg', SINGLE_BLOB) as IMAGE) , "“One tribe, one people, one Freljord.”", 2009-02-21);
INSERT INTO Champion VALUES("Aurelion Sol", 'Other', 'THE STAR FORGER','Celestial', 'Runeterra (Unknown)',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\AurelionSol_0.jpg', SINGLE_BLOB) as IMAGE) , "“Cower. Worship. Marvel. They are all appropriate responses.”", 	2016-03-24);
INSERT INTO Champion VALUES("Azir", 'Male', 'THE EMPEROR OF THE SANDS','Ascended', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Azir_0.jpg', SINGLE_BLOB) as IMAGE) , "“Shurima was once the glory of Runeterra. I will make it so again.”", 2014-09-16);
INSERT INTO Champion VALUES("Bard", 'Other', 'THE WANDERING CARETAKER','Spirit God', 'Runeterra (Unknown)',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Bard_0.jpg', SINGLE_BLOB) as IMAGE) , "“The chimes of his footsteps are echoes of change.”-Ryze", 2015-03-12);
INSERT INTO Champion VALUES("Bel'Veth", 'Female', 'THE EMPRESS OF THE VOID','Voidborn', 'The Void',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Belveth_0.jpg', SINGLE_BLOB) as IMAGE) , "“This world will not be forgotten. I will replace it—a child devouring its parent.”", 2022-06-09);
INSERT INTO Champion VALUES("Blitzcrank", 'Other', 'THE GREAT STEAM GOLEM','Golem', 'Zaun',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Blitzcrank_0.jpg', SINGLE_BLOB) as IMAGE) , "“A SINGLE GEAR TURNING CAN MAKE ALL THE DIFFERENCE.”", 2009-09-02);
INSERT INTO Champion VALUES("Brand", 'Male', 'THE BURNING VENGEANCE','Human', 'Runeterra (Unknown)',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Brand_0.jpg', SINGLE_BLOB) as IMAGE) , "“This place will burn, not by cinder flying or breath of wind, but by the vengeance of my hand.”", 2011-04-12);
INSERT INTO Champion VALUES("Braum", 'Male', 'THE HEART OF THE FRELJORD','Human', 'Freljord',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Braum_0.jpg', SINGLE_BLOB) as IMAGE) , "“Today, we fight as enemies. Tomorrow, we may fight as brothers.”", 2014-05-12);

INSERT INTO Champion VALUES('Caitlyn', 'Female','THE SHERIFF OF PILTOVER','Human', 'Piltover', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Caitlyn_0', SINGLE_BLOB) as IMAGE), 'Boom. Headshot.', 2011-01-04);
INSERT INTO Champion VALUES('Camille', 'Female','THE STEEL SHADOW','Cyborg', 'Piltover',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Camille_0', SINGLE_BLOB) as IMAGE),'Precision is the difference between a butcher and a surgeon.', 2016-12-07);
INSERT INTO Champion VALUES('Cassiopeia', 'Female',"THE SERPENT'S EMBRACE",'Human', 'Noxus', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Cassiopeia_0', SINGLE_BLOB) as IMAGE), 'They will regret opposing me.', 2010-12-14);
INSERT INTO Champion VALUES("Cho'Gath", 'Other','THE TERROR OF THE VOID','Voidborn', 'The Void', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\ChoGath_0', SINGLE_BLOB) as IMAGE), 'Time to feast!', 2009-06-26);
INSERT INTO Champion VALUES('Corki', 'Male','THE DARING BOMBARDIER','Yordle', 'Bandle City', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Corki_0', SINGLE_BLOB) as IMAGE), 'I got a bogey on my tail!', 2009-09-19);

INSERT INTO Champion VALUES('Darius', 'Male','THE HAND OF NOXUS','Human', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Darius_0.jpg', SINGLE_BLOB) as IMAGE), 'Without mercy.',2012-05-23);
INSERT INTO Champion VALUES('Diana', 'Female','SCORN OF THE MOON','Aspect Host', 'Targon',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Diana_0.jpg', SINGLE_BLOB) as IMAGE), 'We feel the heat of the sun, but we do not see the hand that warms us.', 2012-08-07);
INSERT INTO Champion VALUES('Dr. Mundo', 'Male','THE MADMAN OF ZAUN','Mutant Human', 'Zaun',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\DrMundo_0.jpg', SINGLE_BLOB) as IMAGE), 'Mundo says his own name a lot, or else he forgets! Has happened before.',2009-09-02);
INSERT INTO Champion VALUES('Draven', 'Male','THE GLORIOUS EXECUTIONER','Human', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Draven_0.jpg', SINGLE_BLOB) as IMAGE), 'Welcome to the League of Draven.',2012-06-06);

INSERT INTO Champion VALUES('Ekko', 'Male','THE BOY WHO SHATTERED TIME','Human', 'Zaun',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Ekko_0', SINGLE_BLOB) as IMAGE) , 'Every second matters.', 2015-05-28);
INSERT INTO Champion VALUES('Elise', 'Female','THE SPIDER QUEEN','Human', 'Shadow Isles',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Elise_0', SINGLE_BLOB) as IMAGE) , "Come closer... I don't bite.", 2012-10-25);
INSERT INTO Champion VALUES('Evelynn', 'Female',"AGONY'S EMBRACE",'Demon', 'Runeterra (Unknown)',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Evelynn_0', SINGLE_BLOB) as IMAGE) , "I don't break hearts. I just tear them from ribcages.", 2010-05-01);
INSERT INTO Champion VALUES('Ezreal', 'Male','THE PRODIGAL EXPLORER','Human', 'Piltover',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Ezreal_0', SINGLE_BLOB) as IMAGE) , 'Time to make an appearance.', 2010-03-15);

INSERT INTO Champion VALUES('Fiddlesticks', 'Other', 'THE ANCIENT FEAR', 'Demon', 'Runeterra (Unknown)', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Fiddlesticks_0', SINGLE_BLOB) as IMAGE), 'Your bidding, master!', 2009-02-21);
INSERT INTO Champion VALUES('Fiora', 'Female', 'THE GRAND DUELIST', 'Human', 'Demacia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Fiora_0', SINGLE_BLOB) as IMAGE), 'I long for a worthy opponent.', '2012-02-29');
INSERT INTO Champion VALUES('Fizz', 'Male', 'THE TIDAL TRICKSTER', 'Yordle', 'Bilgewater', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Fizz_0', SINGLE_BLOB) as IMAGE), "Let me at ‘em!", 2011-11-15);

INSERT INTO Champion VALUES('Galio', 'Other', 'THE COLOSSUS', 'Gargoyle', 'Demacia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Galio_0.jpg', SINGLE_BLOB) as IMAGE), "That's me! I am protecting!" , 2010-08-10);
INSERT INTO Champion VALUES('Gangplank', 'Male', 'THE SALTWATER SCOURGE', 'Human', 'Bilgewater', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Gangplank_0.jpg', SINGLE_BLOB) as IMAGE), 'Neither the flames nor the depths could claim me.', 2009-08-19);
INSERT INTO Champion VALUES('Garen', 'Male', 'THE MIGHT OF DEMACIA', 'Human', 'Demacia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Garen_0.jpg', SINGLE_BLOB) as IMAGE), 'My heart and sword, always for Demacia.', 2010-04-27);
INSERT INTO Champion VALUES('Gnar', 'Other', 'THE MISSING LINK', 'Yordle', 'Frejlord', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Gnar_0.jpg', SINGLE_BLOB) as IMAGE), '“Gnar!”', 2014-08-14);
INSERT INTO Champion VALUES('Gragas', 'Male', 'THE RABBLE ROUSER', 'Human', 'Frejlord', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Gragas_0.jpg', SINGLE_BLOB) as IMAGE), "My life's purpose, the true meaning of existence, is simply to brew.", 2010-02-02);
INSERT INTO Champion VALUES('Graves', 'Male', 'THE OUTLAW', 'Human', 'Bilgewater', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Graves_0.jpg', SINGLE_BLOB) as IMAGE), "“We're here for your gold, not your heads… so don't nobody decide to be a hero.”", 2011-10-19);
INSERT INTO Champion VALUES('Gwen', 'Other', 'THE HALLOWED SEAMSTRESS', 'Human', 'Shadow Isles', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Gwen_0.jpg', SINGLE_BLOB) as IMAGE), 'Once I loved a queen… and now I will love all.', 2021-04-14);

INSERT INTO Champion VALUES('Hecarim', 'Other','THE SHADOW OF WAR','Spectral Rider', 'Shadow Isles',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Hecarim_0.jpg', SINGLE_BLOB) as IMAGE), 'Break their ranks and ride them down without mercy. Crush the living and feast on their terror.', 2012-04-18);
INSERT INTO Champion VALUES('Heimerdinger', 'Male', 'THE REVERED INVENTOR', 'Yordle', 'Piltover',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Heimerdinger_0.jpg', SINGLE_BLOB) as IMAGE), 'But fear not! Observe the chrono displacement capacitor I have just added. They shall not get the better of us again!', 2009-10-10);

INSERT INTO Champion VALUES('Illaoi', 'Female', 'THE KRAKEN PRIESTESS', 'Human', 'Bilgewater',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Illaoi_0.jpg', SINGLE_BLOB) as IMAGE), 'Life is too short for fear!', 2015-11-24);
INSERT INTO Champion VALUES('Irelia', 'Female', 'The Blade Dancer', 'Human', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Irelia_0.jpg', SINGLE_BLOB) as IMAGE), "My dance has forty-two forms. They'll only see one.", 2010-11-16);
INSERT INTO Champion VALUES('Ivern', 'Male', 'The Green Father', 'Human', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Ivern_0.jpg', SINGLE_BLOB) as IMAGE), 'Slow down. Look around you. Breathe.', 2016-10-05);

INSERT INTO Champion VALUES('Janna', 'Female', "THE STORM'S FURY", 'Spirit God', 'Zaun', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Janna_0.jpg', SINGLE_BLOB) as IMAGE), 'The tempest is at my command!', 2009-09-02);
INSERT INTO Champion VALUES('Jarvan IV', 'Male', 'THE EXEMPLARY DEMACIAN', 'Human', 'Demacia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\JarvanIV_0.jpg', SINGLE_BLOB) as IMAGE), 'By my will, this shall be finished.', 2011-03-01);

INSERT INTO Champion VALUES('Jax', 'Male', 'GRANDMASTER AT ARMS', 'Other', 'Runeterra (Unknown)', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Jax_0.jpg', SINGLE_BLOB) as IMAGE), "Let me at 'em!", 2009-02-21);
INSERT INTO Champion VALUES('Jayce', 'Male', 'THE DEFENDER OF TOMORROW', 'Human', 'Piltover', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Jayce_0.jpg', SINGLE_BLOB) as IMAGE), 'I fight for a brighter tomorrow.', 2012-07-07);
INSERT INTO Champion VALUES('Jhin', 'Male', 'THE VIRTUOSO', 'Human', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Jhin_0.jpg', SINGLE_BLOB) as IMAGE), '“Art requires a certain… cruelty.”', 2016-02-01);
INSERT INTO Champion VALUES('Jinx', 'Female', 'THE LOOSE CANNON', 'Human', 'Zaun', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Jinx_0.jpg', SINGLE_BLOB) as IMAGE), 'What if I had a gun... that shot other guns?', 2013-10-10);

INSERT INTO Champion VALUES("Kai'Sa", 'Female','DAUGHTER OF THE VOID','Human - Void Hybrid', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Kaisa_0', SINGLE_BLOB) as IMAGE) , 'Survival means blending into all sorts of surroundings.', 2018-03-07);
INSERT INTO Champion VALUES('Kalista', 'Female','THE SPEAR OF VENGEANCE','Wraith', 'Shadow Isles',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Kalista_0', SINGLE_BLOB) as IMAGE) , 'When wronged, we seek justice. When hurt, we strike back.', 2014-11-20);
INSERT INTO Champion VALUES('Karma', 'Female','THE ENLIGHTENED ONE','Human', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Karma_0', SINGLE_BLOB) as IMAGE) , 'Never fear change. We are who we must be.', 2011-02-01);
INSERT INTO Champion VALUES('Karthus', 'Male','THE DEATHSINGER','Wraith', 'Shadow Isles',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Karthus_0', SINGLE_BLOB) as IMAGE) , 'Death is not the end of the journey, it is just the beginning...', 2009-06-12);
INSERT INTO Champion VALUES('Kassadin', 'Male','THE VOID WALKER','Human - Void Hybrid', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Kassadin_0', SINGLE_BLOB) as IMAGE) , 'The Void consumes all life. None can resist.', 2009-08-07);
INSERT INTO Champion VALUES('Katarina', 'Female','THE SINISTER BLADE','Human', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Katarina_0', SINGLE_BLOB) as IMAGE) , "There's a thin line between being a hero and a memory.", 2009-09-19);
INSERT INTO Champion VALUES('Kayle', 'Female','THE RIGHTEOUS','Human', 'Targon',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Kayle_0', SINGLE_BLOB) as IMAGE) , 'I will bring them an opera of death!', 2009-02-21);
INSERT INTO Champion VALUES('Kayn', 'Male','THE SHADOW REAPER','Human', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Kayn_0', SINGLE_BLOB) as IMAGE) , '“The child is gone. The killer remains.”', 2017-07-12);
INSERT INTO Champion VALUES('Kennen', 'Male','THE HEART OF THE TEMPEST','Yordle', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Kennen_0', SINGLE_BLOB) as IMAGE) , 'Energy never dies, it only changes.', 2010-04-08);
INSERT INTO Champion VALUES("Kha'Zix", 'Male','THE VOIDREAVER','Voidborn', 'The Void',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Khazix_0', SINGLE_BLOB) as IMAGE) , "They'll never see me coming. It's just the next step in the great cycle.", 2012-09-27);
INSERT INTO Champion VALUES('Kindred', 'Other','THE ETERNAL HUNTERS','Spirit God', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Kindred_0', SINGLE_BLOB) as IMAGE) , '“Tell me again, little Lamb, which things are ours to take?” “All things, dear Wolf.”', 2015-10-14);
INSERT INTO Champion VALUES('Kled', 'Male','THE CANTANKEROUS CAVALIER','Yordle', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Kled_0', SINGLE_BLOB) as IMAGE) , 'There are three certainties in life: a fool trying to intervene, and death!', 2016-08-10);
INSERT INTO Champion VALUES("Kog'Maw", 'Male','THE MOUTH OF THE ABYSS','Voidborn', 'The Void',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Kogmaw_0', SINGLE_BLOB) as IMAGE) , "“If that's just hungry, I don't want to see angry.”", 2010-06-24);
INSERT INTO Champion VALUES("K'Sante'", 'Male','THE PRIDE OF NAZUMAH','Human', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\KSante_0', SINGLE_BLOB) as IMAGE) , "“No monster greater than pride.”", 2022-11-02);

INSERT INTO Champion VALUES("LeBlanc'", 'Female','THE DECEIVER','Human', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Leblanc_0', SINGLE_BLOB) as IMAGE) , "“A rose cannot grow in darkness. It dies, and the darkness grows…”",2010-11-02);
INSERT INTO Champion VALUES('Lee Sin', 'Male', 'THE BLIND MONK', 'Human', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\LeeSin_0.jpg', SINGLE_BLOB) as IMAGE), 'Master yourself... master the enemy.', 2011-04-01);
INSERT INTO Champion VALUES('Leona', 'Female', 'THE RADIANT DAWN', 'Aspect Host', 'Targon', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Leona_0.jpg', SINGLE_BLOB) as IMAGE), 'Next time, try to leave a dent.', 2011-07-13);
INSERT INTO Champion VALUES('Lillia', 'Female', 'THE BASHFUL BLOOM', 'Vastayan', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Lillia_0.jpg', SINGLE_BLOB) as IMAGE), "“When the humans bloom, it's so beautiful… I can help them! Maybe. Possibly? Perhaps…”", 2020-07-22);
INSERT INTO Champion VALUES('Lissandra', 'Female', 'THE ICE WITCH', 'Human', 'Freljord', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Lissandra_0.jpg', SINGLE_BLOB) as IMAGE), 'Close your eyes and let the cold take you...', 2013-04-30);
INSERT INTO Champion VALUES('Lucian', 'Male', 'THE PURIFIER', 'Human', 'Demacia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Lucian_0.jpg', SINGLE_BLOB) as IMAGE), 'Everybody dies... some just need a little help.', 2013-08-22);
INSERT INTO Champion VALUES('Lulu', 'Female', 'THE FAE SORCERESS', 'Yordle', 'Bandle City', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Lulu_0.jpg', SINGLE_BLOB) as IMAGE), 'Yup, that tasted purple!', 2012-03-20);
INSERT INTO Champion VALUES('Lux', 'Female', 'THE LADY OF LUMINOSITY', 'Human', 'Demacia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Lux_0.jpg', SINGLE_BLOB) as IMAGE), 'A double rainbow is a phenomenon of optics that displays a spectrum of light due to the sun shining on droplets of moisture in the atmosphere. Does that explain it?', 2010-10-19);

INSERT INTO Champion VALUES('Malphite', 'Male','SHARD OF THE MONOLITH','Golen', 'Ixtal',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Malphite_0', SINGLE_BLOB) as IMAGE) , '“Beware, minions of chaos! The Shard of the Monolith has come.”', 2009-09-02);
INSERT INTO Champion VALUES('Malzahar', 'Male','THE PROPHET OF THE VOID','Human - Void Hybrid', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Malzahar_0', SINGLE_BLOB) as IMAGE) , 'Bow to the Void, or be consumed by it!', 2010-06-01);
INSERT INTO Champion VALUES('Maokai', 'Male','THE TWISTED TREANT','Treant', 'Shadow Isles',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Maokai_0', SINGLE_BLOB) as IMAGE) , '“All around me are empty husks, soulless and unafraid... but I will bring them fear.”', 2011-02-16);
INSERT INTO Champion VALUES('Master Yi', 'Male','THE WUJU BLADESMAN','Human', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Masteryi_0', SINGLE_BLOB) as IMAGE) , 'The focused mind can pierce through stone.', 2009-02-21);
INSERT INTO Champion VALUES('Milio', 'Male','THE GENTLE FLAME','Human', 'Ixtal',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Milio_0', SINGLE_BLOB) as IMAGE) , "The light inside us, our inner flame... That's the heart of my fire.", 2023-03-23);
INSERT INTO Champion VALUES('Miss Fortune', 'Female','THE BOUNTY HUNTER','Human', 'Bilgewater',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Missfortune_0', SINGLE_BLOB) as IMAGE) , "Fortune doesn't favor fools.", 2010-09-08);
INSERT INTO Champion VALUES('Mordekaiser', 'Other','THE IRON REVENANT','Revenant', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Mordekaiser_0', SINGLE_BLOB) as IMAGE) , '“Destiny. Domination. Deceit.”', 2010-02-24);
INSERT INTO Champion VALUES('Morgana', 'Female','THE FALLEN','Ascended', 'Demacia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Morgana_0', SINGLE_BLOB) as IMAGE) , 'I find beauty in these shadows.', 2009-02-21);

INSERT INTO Champion VALUES("Nasus", 'Male', 'THE CURATOR OF THE SANDS','Ascended', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Nasus_0.jpg', SINGLE_BLOB) as IMAGE) , "“For centuries, I have watched. We approach a time of reckoning.”", 2009-10-01);
INSERT INTO Champion VALUES('Nautilus', 'Male','THE TITAN OF THE DEPTHS','Human', 'Bilgewater',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Nautilus_0', SINGLE_BLOB) as IMAGE), 'Beware the depths.', 2012-02-14);
INSERT INTO Champion VALUES('Neeko', 'Female','THE CURIOUS CHAMELEON','Vastayan', 'Ixtal',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Neeko_0', SINGLE_BLOB) as IMAGE), 'If Neeko becomes Neeko, what does Neeko become?', 2018-12-05);
INSERT INTO Champion VALUES('Nidalee', 'Female','THE BESTIAL HUNTRESS','Human', 'Ixtal',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Nidalee_0', SINGLE_BLOB) as IMAGE), '“The untamed know no fear.”', 2009-12-17);
INSERT INTO Champion VALUES('Nilah', 'Female','THE JOY UNBOUND','Human', 'Bilgewater',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Nilah_0', SINGLE_BLOB) as IMAGE), '“Bliss in life, and bliss forever after.”', 2022-07-13);
INSERT INTO Champion VALUES('Nocturne', 'Other','THE ETERNAL NIGHTMARE','Demon', 'Runeterra (Unknown)',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Nocturne_0', SINGLE_BLOB) as IMAGE), 'The darkness is closing in...', 2011-03-15);
INSERT INTO Champion VALUES('Nunu & Willump', 'Male','THE BOY AND HIS YETI','Human & Yeti', 'Freljord',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Nunu_0', SINGLE_BLOB) as IMAGE), '“Pull the fur outta your earholes, Willump! This is gonna be the bestest story ever!”', 2009-02-21);

INSERT INTO Champion VALUES('Olaf', 'Male', 'THE BERSERKER', 'Human', 'Freljord', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Olaf_0.jpg', SINGLE_BLOB) as IMAGE), 'When you meet your ancestors, tell them Olaf sent you.', 2010-06-09); 
INSERT INTO Champion VALUES('Orianna', 'Female', 'THE LADY OF CLOCKWORK', 'Golem', 'Piltover', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Orianna_0.jpg', SINGLE_BLOB) as IMAGE), '“When a moth emerges from its chrysalis, does it remember its life as a caterpillar?”', 2011-12-13);
INSERT INTO Champion VALUES('Ornn', 'Male', 'THE FIRE BELOW THE MOUNTAIN', 'Spirit God', 'Freljord', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Ornn_0.jpg', SINGLE_BLOB) as IMAGE), '“I have said enough.”', 2017-08-23);

INSERT INTO Champion VALUES('Pantheon', 'Male','THE UNBREAKABLE SPEAR','Human', 'Targon',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Pantheon_0', SINGLE_BLOB) as IMAGE) , '“Here is my eternity… a day the gods will remember!”', 2010-02-02);
INSERT INTO Champion VALUES('Poppy', 'Female','KEEPER OF THE HAMMER','Yordle', 'Bandle City',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Poppy_0', SINGLE_BLOB) as IMAGE) , 'I must stay on the path to find the hero.', 2010-01-13);
INSERT INTO Champion VALUES('Pyke', 'Male','THE BLOODHARBOR RIPPER','Undead', 'Bilgewater',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Pyke_0', SINGLE_BLOB) as IMAGE) , "“There's plenty of room for everyone at the bottom of the sea...”", 2018-05-31);

INSERT INTO Champion VALUES('Qiyana', 'Female', 'EMPRESS OF THE ELEMENTS', 'Human', 'Ixtal', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Qiyana_0.jpg', SINGLE_BLOB) as IMAGE), 'As I breathe, so does Ixtal!', 2019-06-28);
INSERT INTO Champion VALUES('Quinn', 'Female', "DEMACIA'S WINGS", 'Human', 'Demacia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Quinn_0.jpg', SINGLE_BLOB) as IMAGE), 'Justice takes flight.', 2013-03-01);

INSERT INTO Champion VALUES('Rakan', 'Male', 'THE CHARMER', 'Vastayan', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Rakan_0.jpg', SINGLE_BLOB) as IMAGE), "“I got freedom. I got a lady. I got a cause I'd die for.”", 2017-04-19);
INSERT INTO Champion VALUES('Rammus', 'Other', 'THE ARMODILLO', 'Magical Creature', 'Shurima', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Rammus_0.jpg', SINGLE_BLOB) as IMAGE), 'Ok', 2009-07-10);
INSERT INTO Champion VALUES("Rek'Sai", 'Female', 'THE VOID BURROWER', 'Voidborn', 'The Void', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\RekSai_0.jpg', SINGLE_BLOB) as IMAGE), "“Fear not ambush from the hills, nor winged beasts from the skies. The true terror of Shurima comes from the sand, and gives no warning of her presence.” - Sivir", 2014-12-11);
INSERT INTO Champion VALUES('Rell', 'Female', 'THE IRON MAIDEN', 'Human', 'Noxus', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Rell_0.jpg', SINGLE_BLOB) as IMAGE), '“Forge your heart into something strong. Unbreakable.”', 2020-12-10);
INSERT INTO Champion VALUES('Renata Glasc', 'Female', 'THE CHEM-BARONESS', 'Human', 'Zaun', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Renata_0.jpg', SINGLE_BLOB) as IMAGE), "“We don't have to be enemies. Let me change your mind.”", 2022-02-17);
INSERT INTO Champion VALUES('Renekton', 'Male', 'THE BUTCHER OF THE SANDS', 'Ascended', 'Shurima', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Renekton_0.jpg', SINGLE_BLOB) as IMAGE), 'What is broken can be reforged… such is our curse.', 2011-01-18);
INSERT INTO Champion VALUES('Rengar', 'Male', 'THE PRIDESTALKER', 'Kiilash', 'Ixtal', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Rengar_0.jpg', SINGLE_BLOB) as IMAGE), 'Truly elite warriors, hunters of the rarest prey, can never be sated by lesser marks.', 2012-08-21);
INSERT INTO Champion VALUES('Riven', 'Female', 'THE EXILE', 'Human', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Riven_0.jpg', SINGLE_BLOB) as IMAGE), "“A warrior's blade reflects the truth in their heart. Mine is black, and broken.”", 2011-09-14);
INSERT INTO Champion VALUES('Rumble', 'Male', 'THE MECHANIZED MENACE', 'Yordle', 'Bandle City', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Rumble_0.jpg', SINGLE_BLOB) as IMAGE), "Ugh, it's gonna take forever to scrape your face off my suit!", 2011-04-26);
INSERT INTO Champion VALUES('Ryze', 'Male', 'THE RUNE MAGE', 'Human', 'Runeterra (Unknown)', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Ryze_0.jpg', SINGLE_BLOB) as IMAGE), '“Take care with this world. What is made can be unmade.”', 2009-02-21);

INSERT INTO Champion VALUES('Samira', 'Female','THE DESERT ROSE','Human', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Samira_0.jpg', SINGLE_BLOB) as IMAGE) , 'You only live once. Pass the drink.', 2020-09-21);
INSERT INTO Champion VALUES('Sejuani', 'Female','FURY OF THE NORTH','Human', 'Freljord',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Sejuani_0.jpg', SINGLE_BLOB) as IMAGE) , 'Victory is what I live for.', 2012-01-17);
INSERT INTO Champion VALUES('Senna', 'Female','THE REDEEMER','Human', 'Runeterra (Unknown)',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Senna_0.jpg', SINGLE_BLOB) as IMAGE) , 'No more running from the past.', 2019-11-10);
INSERT INTO Champion VALUES('Seraphine', 'Female','THE STAR RYTHM','Human', 'Piltover',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Seraphine_0.jpg', SINGLE_BLOB) as IMAGE) , "“This one's for you!”", 2020-10-29);
INSERT INTO Champion VALUES('Sett', 'Male','THE BOSS','Vastayan', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Sett_0.jpg', SINGLE_BLOB) as IMAGE) , 'I like my enemies two ways: about to die, or dead.', 2019-12-12);
INSERT INTO Champion VALUES('Shaco', 'Other','THE DEMON JESTER','Demon', 'Runeterra (Unknown)',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Shaco_0.jpg', SINGLE_BLOB) as IMAGE) , 'The jokes on you!', 2009-10-10);
INSERT INTO Champion VALUES('Shen', 'Male',"TWILIGHT'S WARDEN",'Human', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Shen_0.jpg', SINGLE_BLOB) as IMAGE) , 'The Eye is blind to itself.', 2010-03-24);  
INSERT INTO Champion VALUES('Shyvana', 'Female','THE HALF-DRAGON','Dragonborn', 'Demacia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Shyvana_0.jpg', SINGLE_BLOB) as IMAGE) , 'On wings of fury.', 2011-11-01);
INSERT INTO Champion VALUES('Singed', 'Male','THE MAD CHEMIST','Human', 'Zaun',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Singed_0.jpg', SINGLE_BLOB) as IMAGE) , 'They laughed at my formulas. Now they tremble at the result.', 2009-04-18);
INSERT INTO Champion VALUES('Sion', 'Other','THE UNDEAD JUGGERNAUT','Undead', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Sion_0.jpg', SINGLE_BLOB) as IMAGE) , 'Blood is the wine of victory.', 2009-02-21);
INSERT INTO Champion VALUES('Sivir', 'Female','THE BATTLE MISTRESS','Human', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Sivir_0.jpg', SINGLE_BLOB) as IMAGE) , 'Fortune favors the bold.', 2009-02-21);
INSERT INTO Champion VALUES('Skarner', 'Other','THE CRYSTAL VANGUARD','Brackern', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Skarner_0.jpg', SINGLE_BLOB) as IMAGE) , 'We await our time.', 2011-08-09);
INSERT INTO Champion VALUES('Sona', 'Female','MAVEN OF THE STRINGS','Human', 'Demacia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Sona_0.jpg', SINGLE_BLOB) as IMAGE) , 'Only you can hear me, summoner. What art truly requires?', 2010-09-21);
INSERT INTO Champion VALUES('Soraka', 'Female','STARCHILD','Celestial', 'Targon',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Soraka_0.jpg', SINGLE_BLOB) as IMAGE) , 'Peace is the way of the stars.', 2009-02-21);
INSERT INTO Champion VALUES('Swain', 'Male','NOXUS: GRAND GENERAL','Human', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Swain_0.jpg', SINGLE_BLOB) as IMAGE) , 'I am war.', 2010-10-05);
INSERT INTO Champion VALUES('Sylas', 'Male', 'THE UNSHACKLED', 'Human', 'Demacia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Sylas_0.jpg', SINGLE_BLOB) as IMAGE), 'No more kings, no more queens, no more mage-seekers. It all ends now.', 2019-01-25);
INSERT INTO Champion VALUES('Syndra', 'Female','THE DARK SOVEREIGN','Human', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Syndra_0.jpg', SINGLE_BLOB) as IMAGE) , 'If power corrupts, I am utterly depraved.', 2012-09-12);

INSERT INTO Champion VALUES('Tahm Kench', 'Male','THE RIVER KING','Demon', 'Bilgewater',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\TahmKench_0.jpg', SINGLE_BLOB) as IMAGE), 'To undo a mistake is easy - ignorance or knowledge, tears or gold.', 2015-07-09);
INSERT INTO Champion VALUES('Taliyah', 'Female','THE STONEWEAVER','Human', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Taliyah_0.jpg', SINGLE_BLOB) as IMAGE), 'I know what my enemies fear about me. They will know it too.', 2016-05-18);
INSERT INTO Champion VALUES('Talon', 'Male',"THE BLADE'S SHADOW",'Human', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Talon_0.jpg', SINGLE_BLOB) as IMAGE), 'The edge is where I walk every day.', 2011-08-24);
INSERT INTO Champion VALUES('Taric', 'Male','THE SHIELD OF VALORAN','Aspect Host', 'Targon',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Taric_0.jpg', SINGLE_BLOB) as IMAGE), "“The best weapons are beautiful.”", 2009-08-19);
INSERT INTO Champion VALUES('Teemo', 'Male','THE SWIFT SCOUT','Yordle', 'Bandle City',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Teemo_0.jpg', SINGLE_BLOB) as IMAGE), "Never underestimate the power of the scout's code!", 2009-02-21);
INSERT INTO Champion VALUES('Thresh', 'Male','THE CHAIN WARDEN','Wraith', 'Shadow Isles',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Thresh_0.jpg', SINGLE_BLOB) as IMAGE), '“The mind is a wondrous thing to tear apart.”', 2013-01-23);
INSERT INTO Champion VALUES('Tristana', 'Female','THE YORDLE GUNNER','Yordle', 'Bandle City',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Tristana_0.jpg', SINGLE_BLOB) as IMAGE), '“Boomer says hi.”', 2009-02-21);
INSERT INTO Champion VALUES('Trundle', 'Male','THE TROLL KING','Troll', 'Freljord',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Trundle_0.jpg', SINGLE_BLOB) as IMAGE), "Outsmart anyone you can't beat, and beat anyone you can't outsmart.", 2010-12-01);
INSERT INTO Champion VALUES('Tryndamere', 'Male','THE BARBARIAN KING','Human', 'Freljord',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Tryndamere_0.jpg', SINGLE_BLOB) as IMAGE), 'Rage is my weapon.', 2009-05-01);
INSERT INTO Champion VALUES('Twisted Fate', 'Male','THE CARD MASTER','Human', 'Bilgewater',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\TwistedFate_0.jpg', SINGLE_BLOB) as IMAGE), 'Every gambler knows the two next best things to winning are smiling and bluffing.', 2009-02-21);
INSERT INTO Champion VALUES('Twitch', 'Male','THE PLAGUE RAT','Vastayan', 'Zaun',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Twitch_0.jpg', SINGLE_BLOB) as IMAGE), "“They threw this away? But it's so shiny!”", 2009-05-01);

INSERT INTO Champion VALUES('Udyr', 'Male','THE SPIRIT WALKER','Human', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Udyr_0.jpg', SINGLE_BLOB) as IMAGE) , 'Every lesson is a gift.', 2009-12-02);
INSERT INTO Champion VALUES('Urgot', 'Male','THE DREADNOUGHT','Human', 'Zaun',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Urgot_0.jpg', SINGLE_BLOB) as IMAGE) , '“There is only one way to measure a man. Tear him… into… pieces.”', 2010-08-24);

INSERT INTO Champion VALUES('Varus', 'Male','THE ARROW OF RETRIBUTION','Darkin', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Varus_0.jpg', SINGLE_BLOB) as IMAGE), "“You didn't destroy us all. And that mistake will be your undoing.”", 2012-05-08);
INSERT INTO Champion VALUES('Vayne', 'Female','THE NIGHT HUNTER','Human', 'Demacia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Vayne_0.jpg', SINGLE_BLOB) as IMAGE), 'Let us hunt those who have fallen to darkness.', 2011-05-10);
INSERT INTO Champion VALUES('Veigar', 'Male','THE TINY MASTER OF EVIL','Yordle', 'Bandle City',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Veigar_0.jpg', SINGLE_BLOB) as IMAGE), 'Even death trembles in my presence!', 2009-07-24);
INSERT INTO Champion VALUES('VelKoz', 'Other','THE EYE OF THE VOID','Voidborn', 'The Void',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\VelKoz_0.jpg', SINGLE_BLOB) as IMAGE), 'Inferior constructs, your time has come.', 2014-02-27);
INSERT INTO Champion VALUES('Vex', 'Female','THE GLOOMIST','Yordle', 'Bandle City',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Vex_0.jpg', SINGLE_BLOB) as IMAGE), '“Just... ughhhhh.”', 2021-09-23);
INSERT INTO Champion VALUES('Vi', 'Female','THE PILTOVER ENFORCER','Human', 'Piltover',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Vi_0.jpg', SINGLE_BLOB) as IMAGE), 'If you hit a wall, hit it hard.', 2012-12-19);
INSERT INTO Champion VALUES('Viego', 'Male','THE RUINED KING','Human', 'Shadow Isles',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Viego_0.jpg', SINGLE_BLOB) as IMAGE), "“No price is too great. No atrocity beyond my reach. For her... I will do anything.”", 2021-01-21);
INSERT INTO Champion VALUES('Viktor', 'Male','THE MACHINE HERALD','Human', 'Zaun',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Viktor_0.jpg', SINGLE_BLOB) as IMAGE), 'Join the glorious evolution.', 2011-12-29);
INSERT INTO Champion VALUES('Vladimir', 'Male','THE CRIMSON REAPER','Hemomancer', 'Noxus',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Vladimir_0.jpg', SINGLE_BLOB) as IMAGE), 'All seems fine before the blood soaks the ground.', 2010-07-27);
INSERT INTO Champion VALUES('Volibear', 'Male','THE RELENTLESS STORM','Spirit God', 'Freljord',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Volibear_0.jpg', SINGLE_BLOB) as IMAGE), 'The storm comes for us all.', 2020-05-28);

INSERT INTO Champion VALUES('Warwick', 'Male', 'THE UNCAGED WRATH OF ZAUN', 'Human', 'Zaun', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Warwick_0.jpg', SINGLE_BLOB) as IMAGE), 'Unrestrained, unchecked, unchained.', 2009-02-21);
INSERT INTO Champion VALUES('Wukong', 'Male', 'THE MONKEY KING', 'Vastayan', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Wukong_0.jpg', SINGLE_BLOB) as IMAGE), '“My journey is only beginning…”', 2011-07-26);

INSERT INTO Champion VALUES('Xayah', 'Female','THE REBEL','Vastayan', 'Ionia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Xayah_0', SINGLE_BLOB) as IMAGE), '“Ever been stabbed by a feather?”', 2017-04-19);
INSERT INTO Champion VALUES('Xerath', 'Other','THE MAGUS ASCENDANT','Ascended', 'Shurima',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Xerath_0', SINGLE_BLOB) as IMAGE), 'I will be the architect of your suffering.', 2011-10-05);
INSERT INTO Champion VALUES('Xin Zhao', 'Male','THE SENESCHAL OF DEMACIA','Human', 'Demacia',(SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\XinZhao_0', SINGLE_BLOB) as IMAGE), 'I will engage them on my terms.', 2010-07-13);

INSERT INTO Champion VALUES('Yasuo', 'Male', 'THE UNFORGIVEN', 'Human', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Yasuo_0.jpg', SINGLE_BLOB) as IMAGE), 'The road to ruin is shorter than you think.', 2013-12-13);
INSERT INTO Champion VALUES('Yone', 'Male', 'THE UNBOUND', 'Human', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Yone_0.jpg', SINGLE_BLOB) as IMAGE), 'Dead or alive, I will settle my past.', 2020-07-24);
INSERT INTO Champion VALUES('Yorick', 'Male', 'SHEPHERD OF SOULS', 'Human', 'Shadow Isles', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Yorick_0.jpg', SINGLE_BLOB) as IMAGE), 'Faces everywhere… those that wear them and the ones that are worn.', 2011-06-22);
INSERT INTO Champion VALUES('Yuumi', 'Female', 'THE MAGICAL CAT', 'Cat', 'Bandle City', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Yuumi_0', SINGLE_BLOB) as IMAGE), "“Cats are made of twilight and tricks, dogs are made of barks and sticks! Book's just old trees.”", 2019-05-14);

INSERT INTO Champion VALUES('Zac', 'Male', 'THE SECRET WEAPON', 'Goo', 'Zaun', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Zac_0', SINGLE_BLOB) as IMAGE), 'This will be messy!', 2013-03-29);
INSERT INTO Champion VALUES('Zed', 'Male', 'THE MASTER OF SHADOWS', 'Human', 'Ionia', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Zed_0', SINGLE_BLOB) as IMAGE), 'The unseen blade is the deadliest.', 2012-11-13);
INSERT INTO Champion VALUES('Zeri', 'Female', 'THE ASPECT OF TWILIGHT', 'Human', 'Zaun', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Zeri_0', SINGLE_BLOB) as IMAGE), '“I belong here. We all belong here.”', 2022-01-20);
INSERT INTO Champion VALUES('Ziggs', 'Male', 'THE HEXPLOSIVES EXPERT', 'Yordle', 'Bandle City', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Ziggs_0', SINGLE_BLOB) as IMAGE), 'Explosion first, questions later.', 2012-02-01);
INSERT INTO Champion VALUES('Zilean', 'Male', 'THE CHRONOKEEPER', 'Human', 'Runeterra (Unknown)', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Zilean_0.jpg', SINGLE_BLOB) as IMAGE), 'Time is a tapestry of our own design.', 2009-04-18);
INSERT INTO Champion VALUES('Zoe', 'Female', 'THE ASPECT OF TWILIGHT', 'Aspect Host', 'Targon', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Zoe_0', SINGLE_BLOB) as IMAGE), '“I bring a message for you all—a warning, a sigil. But first, I wanna see the sparkleflies!”', 2017-11-21);
INSERT INTO Champion VALUES('Zyra', 'Female', 'RISE OF THE THORNS', 'Nature', 'Ixtal', (SELECT * FROM OPENROWSET(BULK 'C:\Users\anawk\Pictures\assets\champs\Zyra_0', SINGLE_BLOB) as IMAGE), 'Death is in bloom.', 2012-07-24);



